export const FIREBASE_EMAIL_PASSWORD_LOGIN_REQUEST = "FIREBASE_EMAIL_PASSWORD_LOGIN_REQUEST";
export const FIREBASE_EMAIL_PASSWORD_LOGIN_SUCCESS = "FIREBASE_EMAIL_PASSWORD_LOGIN_SUCCESS";
export const FIREBASE_EMAIL_PASSWORD_LOGIN_FAILURE = "FIREBASE_EMAIL_PASSWORD_LOGIN_FAILURE";
export const FIREBASE_EMAIL_PASSWORD_SIGNUP_REQUEST = "FIREBASE_EMAIL_PASSWORD_SIGNUP_REQUEST";
export const FIREBASE_EMAIL_PASSWORD_SIGNUP_SUCCESS = "FIREBASE_EMAIL_PASSWORD_SIGNUP_SUCCESS";
export const FIREBASE_EMAIL_PASSWORD_SIGNUP_FAILURE = "FIREBASE_EMAIL_PASSWORD_SIGNUP_FAILURE";
export const FIREBASE_SIGNOUT_REQUEST = "FIREBASE_SIGNOUT_REQUEST";
export const FIREBASE_SIGNOUT_SUCCESS = "FIREBASE_SIGNOUT_SUCCESS";
export const FIREBASE_SIGNOUT_FAILURE = "FIREBASE_SIGNOUT_FAILURE";


