export const SET_CHAT_GPT_RETURN = "SET_CHAT_GPT_RETURN";
export const SET_GPT_API_KEY = "SET_GPT_API_KEY";
export const RESET_TRANS_NEWS_SENTIMENT = "RESET_TRANS_NEWS_SENTIMENT";
export const SET_NEWS_SENTIMENT_REQUEST = "SET_NEWS_SENTIMENT_REQUEST";
export const FETCH_CHAT_GPT_REQUEST = "FETCH_CHAT_GPT_REQUEST";
export const FETCH_CHAT_GPT_SUCCESS = "FETCH_CHAT_GPT_SUCCESS";
export const FETCH_CHAT_GPT_FAILURE = "FETCH_CHAT_GPT_FAILURE";
export const FETCH_CHAT_GPT_4_REQUEST = "FETCH_CHAT_GPT_4_REQUEST";
export const FETCH_CHAT_GPT_4_SUCCESS = "FETCH_CHAT_GPT_4_SUCCESS";
export const FETCH_CHAT_GPT_4_FAILURE = "FETCH_CHAT_GPT_4_FAILURE";
export const FETCH_DOC_GPT_REQUEST = "FETCH_DOC_GPT_REQUEST";
export const FETCH_DOC_GPT_SUCCESS = "FETCH_DOC_GPT_SUCCESS";
export const FETCH_DOC_GPT_FAILURE = "FETCH_DOC_GPT_FAILURE";
export const FETCH_NEWS_SENTIMENT_REQUEST = "FETCH_NEWS_SENTIMENT_REQUEST";
export const FETCH_NEWS_SENTIMENT_SUCCESS = "FETCH_NEWS_SENTIMENT_SUCCESS";
export const FETCH_NEWS_SENTIMENT_FAILURE = "FETCH_NEWS_SENTIMENT_FAILURE";
export const FETCH_NEWS_TRAN_SENTIMENT_REQUEST =
  "FETCH_NEWS_TRAN_SENTIMENT_REQUEST";
export const FETCH_NEWS_TRAN_SENTIMENT_SUCCESS =
  "FETCH_NEWS_TRAN_SENTIMENT_SUCCESS";
export const FETCH_NEWS_TRAN_SENTIMENT_FAILURE =
  "FETCH_NEWS_TRAN_SENTIMENT_FAILURE";
export const FETCH_QNA_REQUEST = "FETCH_QNA_REQUEST";
export const FETCH_QNA_SUCCESS = "FETCH_QNA_SUCCESS";
export const FETCH_QNA_FAILURE = "FETCH_QNA_FAILURE";
export const FIREBASE_UPLOAD_REQUEST = "FIREBASE_UPLOAD_REQUEST";
export const FIREBASE_UPLOAD_SUCCESS = "FIREBASE_UPLOAD_SUCCESS";
export const FIREBASE_UPLOAD_FAILURE = "FIREBASE_UPLOAD_FAILURE";
export const FETCH_FILE_LIST_REQUEST = "FETCH_FILE_LIST_REQUEST";
export const FETCH_FILE_LIST_SUCCESS = "FETCH_FILE_LIST_SUCCESS";
export const FETCH_FILE_LIST_FAILURE = "FETCH_FILE_LIST_FAILURE";

export const DELETE_FILE_FIREBASE_REQUEST = "DELETE_FILE_FIREBASE_REQUEST";
export const DELETE_FILE_FIREBASE_SUCCESS = "DELETE_FILE_FIREBASE_SUCCESS";
export const DELETE_FILE_FIREBASE_FAILURE = "DELETE_FILE_FIREBASE_FAILURE";

export const STOCK_ANALYSIS_REQUEST = "STOCK_ANALYSIS_REQUEST";
export const STOCK_ANALYSIS_SUCCESS = "STOCK_ANALYSIS_SUCCESS";
export const STOCK_ANALYSIS_FAILURE = "STOCK_ANALYSIS_FAILURE";
